### ISSUE TITLE
this library is useless as there is a typo in route.fulfill()

### ISSUE THREAD

**Issue by hydevip** [JijaProGamer/Playwright-cache#1]
there is a typo in this library that breaks the core functionality of this library.

the library calls `route.fullfill` instead of `route.fulfill` according with playwright documentation
<img width="796" alt="image" src="https://github.com/user-attachments/assets/730a4bac-85a9-4d3b-85f3-b9fdf5a07880">
 therefore with this tiny mistake, this library is useless.

faullty line:  https://github.com/JijaProGamer/Playwright-cache/blob/6110972f7516e9a98d82673c5b5cce4c1c24b35d/index.js#L68
` searchFunc(request.url()).then((Data) => {
            if (Data) {
                route.fullfill(Data)
                resolve(true)
            } else {
                resolve(false)
            }`

**Comment by JijaProGamer** [comment]
fix merged

**Comment by hydevip** [comment]
Thank you 😃
